# Generated by Django 2.1.2 on 2018-10-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SighUp',
            new_name='SignUp',
        ),
    ]
