# Generated by Django 2.1.2 on 2018-10-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20181028_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='update',
            new_name='updated',
        ),
    ]
